### PR TITLE
[#174481278] Improve test-bind-template doc

### PR DESCRIPTION
**Pull request by eduardoroliveira**
Co-authored-by: Joe Eltgroth <jeltgroth@vmware.com>

Should this be merged to any other branches? Yes

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @eduardoroliveira and @joeeltgroth 

I did an edit as well as the format fixes. Please review it.

Sometimes it's hard to understand meaning from verb tenses. "Should" is difficult for readers who are new to the subject: Does it mean "Do it" or does it mean "You probably won't do it" as in "you should eat more green leafy vegetables." 

I noticed that you changed step 2 from "Test..." to "You can test..." — I'm assuming that you wanted to indicate that this step is optional.

**Comment by joeeltgroth** [comment]
Thanks!   I took a quick read. I like the removal of the "should"s.   There's a couple little things, and I can PR later this afternoon.  1) "Ensure that ensure that.. ", 2) "bash kubectl create namespace ...": the `bash` should not be visible.

**Comment by jncd** [comment]
Hi @joeeltgroth 
Good catches! I still had the file open so I made those fixes. 
I cherry-picked back to v0.10 but no further because of merge conflicts: the test command is different between v0.10 and v0.9, so might need some expertise.

**Comment by joeeltgroth** [comment]
Thanks!  No worries on backporting then: we can go without

**Pull request merged**
