### PR TITLE
Add 0.11 release notes.

### PR DESCRIPTION
**Pull request by cholick**
Co-authored-by: Emily Johnson <emjohnson@vmware.com>

Should this be merged to any other branches?
> Yes, the `0.11` branch.

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @cholick and @emmjohnson 

One question:



Our style checker flagged this
UAA Client. ==> UAA Command Line Client (UAAC) is preferred for use. UAAC thereafter.

Is the UAA Client that you refer to, the same as the UAA Command Line Client? 

BTW, I'm PRing this directly into the 0-11 branch.

**Comment by cholick** [comment]
No, in this context, a `UUA Client` is an account for a machine (rather than a user)

**Comment by jncd** [comment]
Thanks @cholick 

One more question: What's the "Platform cluster" refer to in the release notes? I didn't find this term elsewhere in the doc — is there another name for it?

**Comment by cholick** [comment]
We've been referring to the k8s cluster that Tanzu Service Manager is installed on as the "Platform cluster" and the cluster in which it provisions services as the "Workload cluster". I'd thought that was the common term in the docks, but maybe that's just what we use internally

**Comment by jncd** [comment]
@cholick 
Thanks! I changed the release notes to say "in the Kubernetes cluster that it is installed on".
I can see that it would be a good idea to have different adjectives to describe the two kinds of cluster. The architecture diagram uses those labels but the terms aren't used elsewhere doc. Something to think about for the 1.0 edit.

**Pull request closed without merging**
