### PR TITLE
Rename product slug to tanzu-service-manager

### PR DESCRIPTION
**Pull request by emmjohnson**
Co-authored-by: Eduardo Oliveira<edeoliveira@vmware.com>

Should this be merged to any other branches? Yes

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @emmjohnson 
How many of the old branches do you want this moved back to?

@saraarntz  I'm thinking that now might be a good time to remove some of the early betas.
Do you know which betas your most important customers are using? 

It's usual to collapse all pre-GA doc into one — say keep the 0.10 doc and copy all the release notes from 0.5 thru to 0.9 into the 0.10 release notes.

**Comment by jncd** [comment]
I could see that the product name on the Tanzu Network had changed but the name of the download file had not.

**Comment by saraarntz** [comment]
I think it’s fair to assume any customer who was actively working with KSM in beta was doing so with .7 and above. I looked at our tile downloads and it seems that the customers we have chatted with are on .7 and above. We can probably remove anything earlier than that.

In terms of the pre-GA doc, I think we can collapse as usual.

Sara

**Comment by jncd** [comment]
@emmjohnson and @eduardoroliveira 
I was able to cherry-pick this back to 0.10 but due to merge conflicts I didn't go back further. 
Could you put in PRs for the earlier versions that need to be addressed?
Thanks!

**Comment by emmjohnson** [comment]
Do we think this is necessary to cherry pick back that far? These are all beta releases.
________________________________

**Pull request merged**
